package model.enums;

public enum Eventos {
    CAMBIO_ESPERANDO_JUGADORES,
    CAMBIO_BUSCAR_PARTIDA,
    ACTUALIZACION_CARTA,
    CAMBIO_TURNO,
    GAME_OVER,
    GAME_WIN,
    DESCONEXION_E,
    DESCONEXION_J,
    RECONEXION_E,
    RECONEXION_J
}
