/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frames;

import view.vistas.VistaGrafica;

/**
 *
 * @author miqueas
 */
public class Menu extends javax.swing.JFrame {
    private VistaGrafica vistaGrafica;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    
    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vMenu = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonReglas = new javax.swing.JButton();
        labelBackgroundMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJugar.setBackground(new java.awt.Color(255, 255, 255));
        botonJugar.setFont(new java.awt.Font("RETROTECH", 0, 48)); // NOI18N
        botonJugar.setForeground(new java.awt.Color(255, 255, 255));
        botonJugar.setText("Jugar");
        botonJugar.setBorder(null);
        botonJugar.setContentAreaFilled(false);
        botonJugar.setFocusPainted(false);
        botonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonJugarMouseExited(evt);
            }
        });
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        vMenu.add(botonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 60));

        botonReglas.setBackground(new java.awt.Color(255, 255, 255));
        botonReglas.setFont(new java.awt.Font("RETROTECH", 0, 48)); // NOI18N
        botonReglas.setForeground(new java.awt.Color(255, 255, 255));
        botonReglas.setText("Reglas");
        botonReglas.setBorder(null);
        botonReglas.setContentAreaFilled(false);
        botonReglas.setFocusPainted(false);
        botonReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReglasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReglasMouseExited(evt);
            }
        });
        botonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReglasActionPerformed(evt);
            }
        });
        vMenu.add(botonReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 160, 60));

        labelBackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/menuGIf.gif"))); // NOI18N
        vMenu.add(labelBackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        getContentPane().add(vMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        setVisible(false);
        vistaGrafica.opciones();
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseEntered
        botonJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_botonJugarMouseEntered

    private void botonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseExited
        botonJugar.setBorder(null);
    }//GEN-LAST:event_botonJugarMouseExited

    private void botonReglasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReglasMouseEntered
        botonReglas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_botonReglasMouseEntered

    private void botonReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReglasMouseExited
        botonReglas.setBorder(null);
    }//GEN-LAST:event_botonReglasMouseExited

    private void botonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReglasActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        vistaGrafica.reglas();
    }//GEN-LAST:event_botonReglasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonReglas;
    private javax.swing.JLabel labelBackgroundMenu;
    private javax.swing.JPanel vMenu;
    // End of variables declaration//GEN-END:variables
}
