/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frames;


import view.vistas.VistaGrafica;

import java.rmi.RemoteException;

/**
 *
 * @author miqueas
 */
public class OpcionesDeJuego extends javax.swing.JFrame {
    private VistaGrafica vistaGrafica;


    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }

    /**
     * Creates new form OpcionesDeJuego
     */
    public OpcionesDeJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jugador1.setVisible(false);
        jugador2.setVisible(false);
        jugador3.setVisible(false);
        jugador4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vOpcionesDeJuego = new javax.swing.JPanel();
        boton2Players = new javax.swing.JButton();
        boton3Players = new javax.swing.JButton();
        boton4Players = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jugador1 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        jugador3 = new javax.swing.JLabel();
        jugador4 = new javax.swing.JLabel();
        labelBackgroundMenu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                try {
                    formWindowClosing(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        vOpcionesDeJuego.setDoubleBuffered(false);
        vOpcionesDeJuego.setOpaque(false);
        vOpcionesDeJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton2Players.setBackground(new java.awt.Color(255, 255, 255));
        boton2Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton2Players.setForeground(new java.awt.Color(255, 255, 255));
        boton2Players.setText("2 Jugadores");
        boton2Players.setBorder(null);
        boton2Players.setContentAreaFilled(false);
        boton2Players.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton2Players.setFocusPainted(false);
        boton2Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton2PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton2PlayersMouseExited(evt);
            }
        });
        boton2Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    boton2PlayersActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        vOpcionesDeJuego.add(boton2Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        boton3Players.setBackground(new java.awt.Color(255, 255, 255));
        boton3Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton3Players.setForeground(new java.awt.Color(255, 255, 255));
        boton3Players.setText("3 Jugadores");
        boton3Players.setBorder(null);
        boton3Players.setContentAreaFilled(false);
        boton3Players.setFocusPainted(false);
        boton3Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton3PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton3PlayersMouseExited(evt);
            }
        });
        boton3Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    boton3PlayersActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        vOpcionesDeJuego.add(boton3Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        boton4Players.setBackground(new java.awt.Color(255, 255, 255));
        boton4Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton4Players.setForeground(new java.awt.Color(255, 255, 255));
        boton4Players.setText("4 Jugadores");
        boton4Players.setBorder(null);
        boton4Players.setContentAreaFilled(false);
        boton4Players.setFocusPainted(false);
        boton4Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4PlayersMouseExited(evt);
            }
        });
        boton4Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    boton4PlayersActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        vOpcionesDeJuego.add(boton4Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setContentAreaFilled(false);
        Volver.setFocusPainted(false);
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/creador_partida/jugador1.png"))); // NOI18N
        vOpcionesDeJuego.add(jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 60, -1));

        jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/creador_partida/jugador2.png"))); // NOI18N
        vOpcionesDeJuego.add(jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 60, 110));

        jugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/creador_partida/jugador3.png"))); // NOI18N
        vOpcionesDeJuego.add(jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/creador_partida/jugador4.png"))); // NOI18N
        vOpcionesDeJuego.add(jugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        labelBackgroundMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/menuGIf.gif"))); // NOI18N
        vOpcionesDeJuego.add(labelBackgroundMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton3PlayersActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException{//GEN-FIRST:event_boton3PlayersActionPerformed
        setVisible(false);
        vistaGrafica.crearPartida(3);
    }//GEN-LAST:event_boton3PlayersActionPerformed

    private void boton2PlayersActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_boton2PlayersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        vistaGrafica.crearPartida(2);
    }//GEN-LAST:event_boton2PlayersActionPerformed

    private void boton4PlayersActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException{//GEN-FIRST:event_boton4PlayersActionPerformed
        setVisible(false);
        vistaGrafica.crearPartida(4);
    }//GEN-LAST:event_boton4PlayersActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        setVisible(false);
        vistaGrafica.opciones();
    }//GEN-LAST:event_VolverActionPerformed
    
    
    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setBorder(null);
    }//GEN-LAST:event_VolverMouseExited

    private void boton2PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2PlayersMouseEntered
        boton2Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jugador1.setVisible(true);
        jugador3.setVisible(true);
    }//GEN-LAST:event_boton2PlayersMouseEntered

    private void boton2PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2PlayersMouseExited
        boton2Players.setBorder(null);
        jugador1.setVisible(false);
        jugador3.setVisible(false);
    }//GEN-LAST:event_boton2PlayersMouseExited

    private void boton3PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3PlayersMouseEntered
        boton3Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jugador1.setVisible(true);
        jugador2.setVisible(true);
        jugador3.setVisible(true);
    }//GEN-LAST:event_boton3PlayersMouseEntered

    private void boton3PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3PlayersMouseExited
        boton3Players.setBorder(null);
        jugador1.setVisible(false);
        jugador2.setVisible(false);
        jugador3.setVisible(false);
    }//GEN-LAST:event_boton3PlayersMouseExited

    private void boton4PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4PlayersMouseEntered
        boton4Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jugador1.setVisible(true);
        jugador2.setVisible(true);
        jugador3.setVisible(true);
        jugador4.setVisible(true);
    }//GEN-LAST:event_boton4PlayersMouseEntered

    private void boton4PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4PlayersMouseExited
        boton4Players.setBorder(null);
        jugador1.setVisible(false);
        jugador2.setVisible(false);
        jugador3.setVisible(false);
        jugador4.setVisible(false);
    }//GEN-LAST:event_boton4PlayersMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) throws RemoteException {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        vistaGrafica.getControlador().cerrar(false);
    }//GEN-LAST:event_formWindowClosing

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton boton2Players;
    private javax.swing.JButton boton3Players;
    private javax.swing.JButton boton4Players;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel jugador3;
    private javax.swing.JLabel jugador4;
    private javax.swing.JLabel labelBackgroundMenu1;
    private javax.swing.JPanel vOpcionesDeJuego;
    // End of variables declaration//GEN-END:variables
}

