/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frames;

import view.vistas.VistaGrafica;

import java.rmi.RemoteException;

/**
 *
 * @author miqueas
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    private VistaGrafica vistaGrafica;


    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vOpciones = new javax.swing.JPanel();
        botonCrearPartida = new javax.swing.JButton();
        botonBuscarPartida = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        labelBackgroundMenu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vOpciones.setDoubleBuffered(false);
        vOpciones.setOpaque(false);
        vOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCrearPartida.setBackground(new java.awt.Color(255, 255, 255));
        botonCrearPartida.setFont(new java.awt.Font("RETROTECH", 0, 32)); // NOI18N
        botonCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearPartida.setText("Crear Partida");
        botonCrearPartida.setBorder(null);
        botonCrearPartida.setContentAreaFilled(false);
        botonCrearPartida.setFocusPainted(false);
        botonCrearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCrearPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCrearPartidaMouseExited(evt);
            }
        });
        botonCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPartidaActionPerformed(evt);
            }
        });
        vOpciones.add(botonCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, 40));

        botonBuscarPartida.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarPartida.setFont(new java.awt.Font("RETROTECH", 0, 32)); // NOI18N
        botonBuscarPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarPartida.setText("Buscar Partida");
        botonBuscarPartida.setBorder(null);
        botonBuscarPartida.setContentAreaFilled(false);
        botonBuscarPartida.setFocusPainted(false);
        botonBuscarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBuscarPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBuscarPartidaMouseExited(evt);
            }
        });
        botonBuscarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botonBuscarPartidaActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        vOpciones.add(botonBuscarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 230, 40));

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setContentAreaFilled(false);
        Volver.setFocusPainted(false);
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        vOpciones.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        labelBackgroundMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/menuGIf.gif"))); // NOI18N
        vOpciones.add(labelBackgroundMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearPartidaMouseEntered
        botonCrearPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_botonCrearPartidaMouseEntered

    private void botonCrearPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearPartidaMouseExited
        botonCrearPartida.setBorder(null);
    }//GEN-LAST:event_botonCrearPartidaMouseExited

    private void botonCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPartidaActionPerformed
        setVisible(false);
        vistaGrafica.opcionesDeJuego();
    }//GEN-LAST:event_botonCrearPartidaActionPerformed

    private void botonBuscarPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarPartidaMouseEntered
        botonBuscarPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_botonBuscarPartidaMouseEntered

    private void botonBuscarPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarPartidaMouseExited
        botonBuscarPartida.setBorder(null);
    }//GEN-LAST:event_botonBuscarPartidaMouseExited

    private void botonBuscarPartidaActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_botonBuscarPartidaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        vistaGrafica.buscarPartidas();
    }//GEN-LAST:event_botonBuscarPartidaActionPerformed

    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setBorder(null);
    }//GEN-LAST:event_VolverMouseExited

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        setVisible(false);
        vistaGrafica.menu();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton botonBuscarPartida;
    private javax.swing.JButton botonCrearPartida;
    private javax.swing.JLabel labelBackgroundMenu1;
    private javax.swing.JPanel vOpciones;
    // End of variables declaration//GEN-END:variables
}
