/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frames;

import model.enums.EstadoPartida;
import model.enums.Estados;
import model.interfaces.IPartida;
import view.vistas.VistaGrafica;

import javax.swing.*;
import java.rmi.RemoteException;
import java.util.Map;

/**
 *
 * @author miqueas
 */
public class Ranking extends javax.swing.JFrame {
    private VistaGrafica vistaGrafica;
    /**
     * Creates new form Menu
     */
    public Ranking() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    
    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vRanking = new javax.swing.JPanel();
        labelRanking = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        panelPartidas = new javax.swing.JPanel();
        labelBackgroundMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                try {
                    formWindowClosing(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        vRanking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRanking.setFont(new java.awt.Font("RETROTECH", 0, 40)); // NOI18N
        labelRanking.setForeground(new java.awt.Color(255, 255, 255));
        labelRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRanking.setText("Ranking");
        vRanking.add(labelRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setContentAreaFilled(false);
        Volver.setFocusPainted(false);
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        vRanking.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        panelPartidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPartidas.setOpaque(false);
        panelPartidas.setLayout(new javax.swing.BoxLayout(panelPartidas, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelPartidas);

        jScrollPane1.setViewportView(panelPartidas);
        vRanking.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 730, 400));

        labelBackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/menu/buscador_partida/buscarPartida.gif"))); // NOI18N
        vRanking.add(labelBackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        getContentPane().add(vRanking, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setBorder(null);
    }//GEN-LAST:event_VolverMouseExited

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        setVisible(false);
        vistaGrafica.opciones();
    }//GEN-LAST:event_VolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) throws RemoteException {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        vistaGrafica.getControlador().cerrar(false);
    }//GEN-LAST:event_formWindowClosing

    public void datosRanking() throws RemoteException{
        panelPartidas.removeAll();
        Map<String, Integer> rank = vistaGrafica.getControlador().getRanking();
        int i = 1;
        for (Map.Entry<String, Integer> entry : rank.entrySet()){
            JLabel label = new JLabel();
            label.setBackground(new java.awt.Color(255, 255, 255));
            label.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
            label.setForeground(new java.awt.Color(255, 255, 255));
            label.setBorder(null);
            label.setText(i + ". " + "Jugador: " + entry.getKey() + "    -    " + entry.getValue() + "  P-G");
            panelPartidas.add(label);
            i++;
        }
        panelPartidas.revalidate();
        panelPartidas.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBackgroundMenu;
    private javax.swing.JLabel labelRanking;
    private javax.swing.JPanel panelPartidas;
    private javax.swing.JPanel vRanking;
    // End of variables declaration//GEN-END:variables
}
