/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.vistagrafica;

import javax.swing.border.BevelBorder;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;

/**
 *
 * @author miqueas
 */
public class OpcionesDeJuego extends javax.swing.JFrame {
    private ImageIcon imagenDosJugadores;
    private ImageIcon imagenTresJugadores;
    private ImageIcon imagenCuatroJugadores;
    private ImageIcon imagenCincoJugadores;
    private ImageIcon imagenOriginal;
    private VistaGrafica vistaGrafica;
    
    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }

    /**
     * Creates new form OpcionesDeJuego
     */
    public OpcionesDeJuego() {
        imagenDosJugadores = new ImageIcon(getClass().getResource("/view/imagenes/2jugadores.png"));
        imagenTresJugadores = new ImageIcon(getClass().getResource("/view/imagenes/3jugadoresbackgroundcorreigod.png"));
        imagenCuatroJugadores = new ImageIcon(getClass().getResource("/view/imagenes/4jugadoresbackground.png"));
        imagenCincoJugadores = new ImageIcon(getClass().getResource("/view/imagenes/5jugadoresbackground.png"));
        imagenOriginal = new ImageIcon(getClass().getResource("/view/imagenes/fondoEstatico.png"));
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vOpcionesDeJuego = new javax.swing.JPanel();
        boton3Players = new javax.swing.JButton();
        boton2Players = new javax.swing.JButton();
        boton4Players = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        boton5Players = new javax.swing.JButton();
        labelBackgroundMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vOpcionesDeJuego.setOpaque(false);
        vOpcionesDeJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton3Players.setBackground(new java.awt.Color(255, 255, 255));
        boton3Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton3Players.setForeground(new java.awt.Color(255, 255, 255));
        boton3Players.setText("3 Jugadores");
        boton3Players.setBorder(null);
        boton3Players.setContentAreaFilled(false);
        boton3Players.setFocusPainted(false);
        boton3Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton3PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton3PlayersMouseExited(evt);
            }
        });
        boton3Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3PlayersActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(boton3Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 50));

        boton2Players.setBackground(new java.awt.Color(255, 255, 255));
        boton2Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton2Players.setForeground(new java.awt.Color(255, 255, 255));
        boton2Players.setText("2 Jugadores");
        boton2Players.setBorder(null);
        boton2Players.setContentAreaFilled(false);
        boton2Players.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton2Players.setFocusPainted(false);
        boton2Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton2PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton2PlayersMouseExited(evt);
            }
        });
        boton2Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2PlayersActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(boton2Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 50));

        boton4Players.setBackground(new java.awt.Color(255, 255, 255));
        boton4Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton4Players.setForeground(new java.awt.Color(255, 255, 255));
        boton4Players.setText("4 Jugadores");
        boton4Players.setBorder(null);
        boton4Players.setContentAreaFilled(false);
        boton4Players.setFocusPainted(false);
        boton4Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4PlayersMouseExited(evt);
            }
        });
        boton4Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4PlayersActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(boton4Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 50));

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setContentAreaFilled(false);
        Volver.setFocusPainted(false);
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, 50));

        boton5Players.setBackground(new java.awt.Color(255, 255, 255));
        boton5Players.setFont(new java.awt.Font("RETROTECH", 0, 36)); // NOI18N
        boton5Players.setForeground(new java.awt.Color(255, 255, 255));
        boton5Players.setText("5 Jugadores");
        boton5Players.setBorder(null);
        boton5Players.setContentAreaFilled(false);
        boton5Players.setFocusPainted(false);
        boton5Players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton5PlayersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton5PlayersMouseExited(evt);
            }
        });
        boton5Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5PlayersActionPerformed(evt);
            }
        });
        vOpcionesDeJuego.add(boton5Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 50));

        labelBackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/file.gif"))); // NOI18N
        vOpcionesDeJuego.add(labelBackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton3PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3PlayersActionPerformed
        boton3Players.setText("pepee");
    }//GEN-LAST:event_boton3PlayersActionPerformed

    private void boton2PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2PlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2PlayersActionPerformed

    private void boton4PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4PlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton4PlayersActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        vistaGrafica.mostrarMenuGrafica();
    }//GEN-LAST:event_VolverActionPerformed
    
    
    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        Volver.setBorder(null);
    }//GEN-LAST:event_VolverMouseExited

    private void boton2PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2PlayersMouseEntered
        boton2Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelBackgroundMenu.setIcon(imagenDosJugadores);
        
    }//GEN-LAST:event_boton2PlayersMouseEntered

    private void boton2PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2PlayersMouseExited
        boton2Players.setBorder(null);
        labelBackgroundMenu.setIcon(imagenOriginal);
    }//GEN-LAST:event_boton2PlayersMouseExited

    private void boton3PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3PlayersMouseEntered
        boton3Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelBackgroundMenu.setIcon(imagenTresJugadores);
    }//GEN-LAST:event_boton3PlayersMouseEntered

    private void boton3PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3PlayersMouseExited
        boton3Players.setBorder(null);
        labelBackgroundMenu.setIcon(imagenOriginal);
    }//GEN-LAST:event_boton3PlayersMouseExited

    private void boton4PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4PlayersMouseEntered
        boton4Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelBackgroundMenu.setIcon(imagenCuatroJugadores);
    }//GEN-LAST:event_boton4PlayersMouseEntered

    private void boton4PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4PlayersMouseExited
        boton4Players.setBorder(null);
        labelBackgroundMenu.setIcon(imagenOriginal);
    }//GEN-LAST:event_boton4PlayersMouseExited

    private void boton5PlayersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5PlayersMouseEntered
        boton5Players.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelBackgroundMenu.setIcon(imagenCincoJugadores);
    }//GEN-LAST:event_boton5PlayersMouseEntered

    private void boton5PlayersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5PlayersMouseExited
        boton5Players.setBorder(null);
        labelBackgroundMenu.setIcon(imagenOriginal);
    }//GEN-LAST:event_boton5PlayersMouseExited

    private void boton5PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5PlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton5PlayersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton boton2Players;
    private javax.swing.JButton boton3Players;
    private javax.swing.JButton boton4Players;
    private javax.swing.JButton boton5Players;
    private javax.swing.JLabel labelBackgroundMenu;
    private javax.swing.JPanel vOpcionesDeJuego;
    // End of variables declaration//GEN-END:variables
}
