/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.vistagrafica;

import model.Partida;
import java.util.List;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author miqueas
 */
public class PartidaEnJuego extends javax.swing.JFrame {
    private List<JPanel> centerZone = new ArrayList<>();
    private List<JPanel> handZone = new ArrayList<>();

    /**
     * Creates new form BuscarPartida
     */
    public PartidaEnJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        inicializarZonas();
        agregarCartasDraggables();
    }

    private VistaGrafica vistaGrafica;


    public void setVistaGrafica(VistaGrafica vistaGrafica){
        this.vistaGrafica = vistaGrafica;
    }


    private void inicializarZonas() {
        // Crear paneles donde se pueden soltar cartas
        centerZone.add(zonaCartaAlta);
        centerZone.add(zonaCartaBaja);

        // Crear paneles donde están las cartas en la mano
        handZone.add(zonaManoCarta1);
        handZone.add(zonaManoCarta2);
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
    }

    private void agregarCartasDraggables() {
        Draggable draggable = new Draggable(carta1, handZone.get(0).getX(), handZone.get(0).getY(), this, centerZone, handZone);
        Draggable draggable2 = new Draggable(carta2, handZone.get(1).getX(), handZone.get(1).getY(), this, centerZone, handZone);
        draggable.setAction(true);
        draggable2.setAction(true);
        this.getContentPane().add(draggable);
        this.getContentPane().add(draggable2);
        this.getContentPane().setComponentZOrder(draggable, 0);
        this.getContentPane().setComponentZOrder(draggable2, 0);
        this.getContentPane().setComponentZOrder(dedo, 0);
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vOpcionesDeJuego = new javax.swing.JPanel();
        mazo = new javax.swing.JButton();
        nombreJugador2 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        zonaCartaAlta = new javax.swing.JPanel();
        zonaCartaBaja = new javax.swing.JPanel();
        zonaManoCarta2 = new javax.swing.JPanel();
        zonaManoCarta1 = new javax.swing.JPanel();
        dedo = new javax.swing.JLabel();
        labelBackgroundMenu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vOpcionesDeJuego.setDoubleBuffered(false);
        vOpcionesDeJuego.setOpaque(false);
        vOpcionesDeJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mazoActionPerformed(evt);
            }
        });
        mazo.setForeground(new java.awt.Color(255, 255, 255));
        mazo.setBorder(null);
        mazo.setContentAreaFilled(false);
        mazo.setFocusPainted(false);
        vOpcionesDeJuego.add(mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 90));

        nombreJugador2.setFont(new java.awt.Font("RETROTECH", 0, 24)); // NOI18N
        nombreJugador2.setForeground(new java.awt.Color(255, 255, 255));
        nombreJugador2.setText("Tato");
        vOpcionesDeJuego.add(nombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        nombreJugador3.setFont(new java.awt.Font("RETROTECH", 0, 24)); // NOI18N
        nombreJugador3.setForeground(new java.awt.Color(255, 255, 255));
        nombreJugador3.setText("Juan");
        vOpcionesDeJuego.add(nombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        nombreJugador4.setFont(new java.awt.Font("RETROTECH", 0, 24)); // NOI18N
        nombreJugador4.setForeground(new java.awt.Color(255, 255, 255));
        nombreJugador4.setText("El trolo de mate");
        vOpcionesDeJuego.add(nombreJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/cartas/azul/AZUL1.png"))); // NOI18N
        vOpcionesDeJuego.add(carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 140, 210));

        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/cartas/blanco/BLANCO10.png"))); // NOI18N
        vOpcionesDeJuego.add(carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, 220));

        zonaCartaAlta.setOpaque(false);

        javax.swing.GroupLayout zonaCartaAltaLayout = new javax.swing.GroupLayout(zonaCartaAlta);
        zonaCartaAlta.setLayout(zonaCartaAltaLayout);
        zonaCartaAltaLayout.setHorizontalGroup(
            zonaCartaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        zonaCartaAltaLayout.setVerticalGroup(
            zonaCartaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        vOpcionesDeJuego.add(zonaCartaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 350, 110));

        zonaCartaBaja.setOpaque(false);

        javax.swing.GroupLayout zonaCartaBajaLayout = new javax.swing.GroupLayout(zonaCartaBaja);
        zonaCartaBaja.setLayout(zonaCartaBajaLayout);
        zonaCartaBajaLayout.setHorizontalGroup(
            zonaCartaBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        zonaCartaBajaLayout.setVerticalGroup(
            zonaCartaBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        vOpcionesDeJuego.add(zonaCartaBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 440, 90));

        zonaManoCarta2.setOpaque(false);

        javax.swing.GroupLayout zonaManoCarta2Layout = new javax.swing.GroupLayout(zonaManoCarta2);
        zonaManoCarta2.setLayout(zonaManoCarta2Layout);
        zonaManoCarta2Layout.setHorizontalGroup(
            zonaManoCarta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        zonaManoCarta2Layout.setVerticalGroup(
            zonaManoCarta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        vOpcionesDeJuego.add(zonaManoCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 140, 190));

        zonaManoCarta1.setOpaque(false);

        javax.swing.GroupLayout zonaManoCarta1Layout = new javax.swing.GroupLayout(zonaManoCarta1);
        zonaManoCarta1.setLayout(zonaManoCarta1Layout);
        zonaManoCarta1Layout.setHorizontalGroup(
            zonaManoCarta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        zonaManoCarta1Layout.setVerticalGroup(
            zonaManoCarta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        vOpcionesDeJuego.add(zonaManoCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 140, 220));

        dedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/mesa/dedonuevo.png"))); // NOI18N
        vOpcionesDeJuego.add(dedo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        labelBackgroundMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/mesa/mesa4jugadores.png"))); // NOI18N
        vOpcionesDeJuego.add(labelBackgroundMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vOpcionesDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mazoActionPerformed
        // TODO add your handling code here:
        System.out.println("TOCO EL MAZO");
    }//GEN-LAST:event_mazoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidaEnJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidaEnJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidaEnJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidaEnJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidaEnJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel dedo;
    private javax.swing.JLabel labelBackgroundMenu1;
    private javax.swing.JButton mazo;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel vOpcionesDeJuego;
    private javax.swing.JPanel zonaCartaAlta;
    private javax.swing.JPanel zonaCartaBaja;
    private javax.swing.JPanel zonaManoCarta1;
    private javax.swing.JPanel zonaManoCarta2;
    // End of variables declaration//GEN-END:variables
}
